services:
  - type: web
    name: job-fraud-detection
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app_:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DB
        sync: false
