services:
  - type: web
    name: job-fraud-detection
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FIREBASE_SERVICE_ACCOUNT_KEY
        sync: false
